#!/bin/bash

SERVICE_NAME="/test_cartesian_path"

# Define waypoints (example: 2 poses)
WAYPOINTS='[{
    position: {x: 0.5, y: 0.0, z: 0.5}, orientation: {x: 1.0, y: 0.0, z: 0.0, w: 0.0}
  },
  {
    position: {x: 0.6, y: 0.0, z: 0.5}, orientation: {x: 1.0, y: 0.0, z: 0.0, w: 0.0}
}]'

# Call the service using ros2 CLI
ros2 service call $SERVICE_NAME object_mover_interfaces/srv/CartesianPathRequest "{waypoints: $WAYPOINTS}"